### ISSUE TITLE
How to assign permission sets to okta groups?

### ISSUE THREAD

**Issue by M10han** [gerardVM/terraform-aws-iam-identity-center#4]
Hello Gerard,

Thanks for creating the tf module for managing identity center resources. I'm still finding my way in the terraform world. I am trying to set up identity center with tf as well. But instead of creating the users/groups in AWS itself, I've configured my identity source as External Identity Provider with Okta. My okta groups are now synced to AWS and show up on Identity Center Console.

Now, I want to do the account assignments to the okta group that is synced to Identity Center. Could you please explain how I could achieve that with this module or is it possible to add that feature?

Thank you

**Comment by gerardVM** [comment]
M10han,

Thanks for using this module. I am sorry but I have no experience with Okta. Having a look at the [documentation ](https://docs.aws.amazon.com/singlesignon/latest/userguide/gs-okta.html) it seems that Okta already manage users and groups. 
This module does not consider this scenario. But I bet it's worth to try [importing](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/identitystore_user#import) the already existing [groups and users](https://github.com/gerardVM/terraform-aws-iam-identity-center/blob/main/groups_users.tf). This may not be the cleanest solution, but my guess is that this approach should let you keep using this module to organize your permissions in its proposed yaml structure.

Good luck with that implementation!

**Comment by mohann10** [comment]
Thanks, Gerard!

Yeah, Okta does manage the users and groups. It's just that I could not think of a good way to assign accounts to the okta group which is not in the code config. I guess I could use the import block to import the group but every time a new group is created, I'll have to keep adding these import blocks. And at this moment, I could think of a better solution. :)

**Comment by gerardVM** [comment]
There is in fact an easier solution. We coud implement an extra variable that decides whether the user or group resources need to be created or just read (data source) given a name.
I'll have a look at that implementation during this week. Thanks for bringing up your usecase!
Feel free to raise a PR if you feel confident enough, by the way.
Cheers

**Comment by gerardVM** [comment]
M10han,

Thanks for using this module. After conducting some tests, I realized that the best approach for your use case is to import your existing groups into this module. This method should work effectively.

```
locals {
  groups            = yamldecode(file("./example_groups.yaml"))
  identity_store_id = "d-1234567890"
}

data "aws_identitystore_group" "groups" {
  for_each          = local.groups
  
  identity_store_id = local.identity_store_id

  alternate_identifier {
    unique_attribute {
      attribute_path  = "DisplayName"
      attribute_value = each.key
    }
  }
}

import {
  for_each = local.groups

  to = module.iam_sso.aws_identitystore_group.groups[each.key]
  id = "${local.identity_store_id}/${data.aws_identitystore_group.groups[each.key].id}"
}
```

Important note: Be aware that IAM Identity Center considers regions, unlike IAM.
Terraform version: >= 1.7.0

**Comment by mohann10** [comment]
Thanks, Gerard!! This all should just work perfect. You're amazing!!

**Comment by M10han** [comment]
Thanks, Gerard!! This all should just work perfect. You're amazing!!
We can close this issue now.
